export const locationsDatas = [
  {
    iframeUrl:
      "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d289737.4884188902!2d-80.4144377!3d25.8105987!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d901f97b6ae0f5%3A0x10d260b14def122c!2sFischer%20Redavid%20PLLC!5e1!3m2!1sen-US!2sbr!4v1730300047176!5m2!1sen-US!2sbr",
    title: "Florida Office",
    address: "3325 Hollywood Blvd,<br>#500<br>Hollywood, FL 33021",
    href: "https://maps.app.goo.gl/EU6t2Sh3fU8hxkvK8",
  },
  {
    iframeUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4175.789182429819!2d-84.379955!3d33.863302700000006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f50fd3c35bc2a3%3A0xffe1db7778b2cc7a!2sFischer%20Redavid%20PLLC!5e1!3m2!1sen!2sbr!4v1730300018834!5m2!1sen!2sbr",
    title: "Georgia Office",
    address: "3975 Roswell Road NE,<br>Suite3<br>Atlanta, GA 30342",
    href: "https://maps.app.goo.gl/vyjvrrbykCDxWYke9",
  },
  {
    iframeUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4773.349309826778!2d-64.9277336!3d18.3418039!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c051be928eb599f%3A0x538aaa62b1705a26!2sFischer%20Redavid%20PLLC!5e1!3m2!1sen!2sbr!4v1730299985549!5m2!1sen!2sbr",
    title: "U.S. Virgin Islands Office",
    address: "15-B Norre Gade,<br>St Thomas, 00804",
    href: "https://maps.app.goo.gl/6We7Pc16XpjkqC7t6",
  },
];

export const courtOptions = [
  {
    title: "11th Circuit Court of Appeals",
    value: "11th-circuit-court-of-appeals",
  },
  { title: "1st DCA", value: "1st-dca" },
  { title: "2nd DCA", value: "2nd-dca" },
  { title: "3rd DCA", value: "3rd-dca" },
  { title: "4th DCA", value: "4th-dca" },
  { title: "5th DCA", value: "5th-dca" },
  { title: "6th DCA", value: "6th-dca" },
  { title: "Georgia Court of Appeals", value: "georgia-court-of-appeals" },
  { title: "Georgia Supreme Court", value: "georgia-supreme-court" },
  { title: "Supreme Court of Florida", value: "supreme-court-of-florida" },
  {
    title: "Supreme Court of the United States of America",
    value: "supreme-court-of-the-united-states-of-america",
  },
  {
    title: "Third Circuit Court of Appeals",
    value: "third-circuit-court-of-appeals",
  },
];

export const categoriesOptions = [
  { title: "18 U.S.C. § 2333", value: "18-usc-2333" },
  { title: "1983 (Eighth Amendment)", value: "1983-eighth-amendment" },
  { title: "1983 (Excessive Force)", value: "1983-excessive-force" },
  { title: "1983 (First Amendment)", value: "1983-first-amendment" },
  { title: "57.105 Sanctions", value: "57-105-sanctions" },
  {
    title: "Adult Protective Services Act",
    value: "adult-protective-services-act",
  },
  { title: "Affirmative Defenses", value: "affirmative-defenses" },
  { title: "Amendment of Pleadings", value: "amendment-of-pleadings" },
  {
    title: "Americans With Disabilities Act",
    value: "americans-with-disabilities-act",
  },
  { title: "Appealable Order", value: "appealable-order" },
  { title: "Arbitration", value: "arbitration" },
  { title: "Attorneys Fees", value: "attorneys-fees" },
  { title: "Bad Faith", value: "bad-faith" },
  { title: "Biomechanical Expert", value: "biomechanical-expert" },
  { title: "Breach of Fiduciary Duty", value: "breach-of-fiduciary-duty" },
  { title: "Business Records", value: "business-records" },
  { title: "Causation", value: "causation" },
  { title: "Certificate of Service", value: "certificate-of-service" },
  { title: "Civil Rights", value: "civil-rights" },
  { title: "Class Actions", value: "class-actions" },
  { title: "Consent Jurisdiction", value: "consent-jurisdiction" },
  { title: "Continuance", value: "continuance" },
  { title: "Contract Interpretation", value: "contract-interpretation" },
  { title: "Corporate Representative", value: "corporate-representative" },
  {
    title: "Corporate Representative Deposition",
    value: "corporate-representative-deposition",
  },
  { title: "Costs", value: "costs" },
  { title: "Defamation", value: "defamation" },
  { title: "Default Judgment", value: "default-judgment" },
  { title: "Directed Verdict", value: "directed-verdict" },
  { title: "Discovery", value: "discovery" },
  {
    title: "Discovery (Sanctions/Violations)",
    value: "discovery-sanctions-violations",
  },
  {
    title: "Disqualification or Recusal of Judge",
    value: "disqualification-or-recusal-of-judge",
  },
  { title: "Examinations Under Oath", value: "examinations-under-oath" },
  { title: "Excessive Force", value: "excessive-force" },
  {
    title: "Exploitation of a Vulnerable Adult (415.111)",
    value: "exploitation-of-a-vulnerable-adult-415-111",
  },
  { title: "Family Medical Leave Act", value: "family-medical-leave-act" },
  {
    title: "First Amendment True Threat",
    value: "first-amendment-true-threat",
  },
  { title: "Florida Civil Rights Claim", value: "florida-civil-rights-claim" },
  { title: "Forum", value: "forum" },
  { title: "Hearsay", value: "hearsay" },
  { title: "Impact Rule", value: "impact-rule" },
  {
    title: "Inequitable Conduct Doctrine",
    value: "inequitable-conduct-doctrine",
  },
  {
    title: "Internet Service Provider Liability",
    value: "internet-service-provider-liability",
  },
  { title: "Intervening Cause", value: "intervening-cause" },
  { title: "Lack of Prosecution", value: "lack-of-prosecution" },
  { title: "Libel", value: "libel" },
  { title: "Malpractice (Legal)", value: "malpractice-legal" },
  { title: "Medicaid Lien", value: "medicaid-lien" },
  { title: "Medical Malpractice", value: "medical-malpractice" },
  {
    title: "Medical Malpractice (Presuit)",
    value: "medical-malpractice-presuit",
  },
  { title: "Motion for New Trial", value: "motion-for-new-trial" },
  { title: "Motion in Limine", value: "motion-in-limine" },
  { title: "Motion to Dismiss", value: "motion-to-dismiss" },
  { title: "Motion to Quash Service", value: "motion-to-quash-service" },
  {
    title: "Motion to Stay; Petition for Certiorari",
    value: "motion-to-stay-petition-for-certiorari",
  },
  { title: "Negligence", value: "negligence" },
  { title: "Negligence/Breach of Duty", value: "negligence-breach-of-duty" },
  { title: "Negligence/Causation", value: "negligence-causation" },
  { title: "Negligence/Damages", value: "negligence-damages" },
  { title: "Negligence/Duty", value: "negligence-duty" },
  { title: "Non-Economic Damages", value: "non-economic-damages" },
  { title: "Non-Final Orders", value: "non-final-orders" },
  { title: "Offer of Judgment", value: "offer-of-judgment" },
  { title: "Personal Jurisdiction", value: "personal-jurisdiction" },
  { title: "Petition for Certiorari", value: "petition-for-certiorari" },
  { title: "Preemption", value: "preemption" },
  { title: "Premises Liability", value: "premises-liability" },
  { title: "Preservation", value: "preservation" },
  { title: "Privilege (Attorney-Client)", value: "privilege-attorney-client" },
  { title: "Privilege (Psychotherapist)", value: "privilege-psychotherapist" },
  { title: "Products Liability", value: "products-liability" },
  { title: "Proximate Cause", value: "proximate-cause" },
  { title: "Punitive Damages", value: "punitive-damages" },
  { title: "Rehearing", value: "rehearing" },
  { title: "Rehearing En Banc", value: "rehearing-en-banc" },
  { title: "Rule 1.540 Motion", value: "rule-1-540-motion" },
  {
    title: "Rules of Civil Procedure (Florida)",
    value: "rules-of-civil-procedure-florida",
  },
  { title: "Sanctions", value: "sanctions" },
  { title: "Service of Process", value: "service-of-process" },
  { title: "Settlement", value: "settlement" },
  { title: "Slip and Fall", value: "slip-and-fall" },
  {
    title: "Sovereign Immunity (Florida)",
    value: "sovereign-immunity-florida",
  },
  { title: "Standing", value: "standing" },
  {
    title: "Statute of Limitations (Florida)",
    value: "statute-of-limitations-florida",
  },
  { title: "Statute of Repose", value: "statute-of-repose" },
  { title: "Structured Settlement", value: "structured-settlement" },
  {
    title: "Subject Matter Jurisdiction",
    value: "subject-matter-jurisdiction",
  },
  { title: "Summary Judgement Standard", value: "summary-judgement-standard" },
  {
    title: "Transitory Foreign Substance",
    value: "transitory-foreign-substance",
  },
  { title: "Venue", value: "venue" },
  { title: "Vicarious Liability", value: "vicarious-liability" },
  { title: "Vulnerable Adult", value: "vulnerable-adult" },
  { title: "Writ of Certiorari", value: "writ-of-certiorari" },
  { title: "Writ of Mandamus", value: "writ-of-mandamus" },
  { title: "Writ of Prohibition", value: "writ-of-prohibition" },
  { title: "Writ of Quo Warranto", value: "writ-of-quo-warranto" },
  { title: "Wrongful Death", value: "wrongful-death" },
];
